apiVersion: v1
kind: Service
metadata:
  name: pi-wcf
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 50505
      targetPort: 50505
---
kind: Endpoints
apiVersion: v1
metadata:
  name: pi-wcf
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.2.119
    ports:
      - port: 50505
