apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-service-account
  namespace: default
  labels:
    app: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-service-account
      containers:
        - image: prom/prometheus:v2.15.2
          name: prometheus
          resources:
            limits:
              cpu: 375m
              memory: 750Mi
          ports:
            - containerPort: 9090
              name: prometheus
          volumeMounts:
            - name: config
              mountPath: "/etc/prometheus/"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: prometheus-configmap
      nodeSelector:
        beta.kubernetes.io/os: linux
